{
    'name': 'Smart Trading Reports',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'author': 'Lakna Attigala',
    'summary': 'Module for generating reports',
    'sequence':'6',
    'maintainer':'flectra mates',
    'website':'https://codeso.lk',
    'depends': [],
    'demo':[],
    'data':['reports/invoice_export_packing_report.xml',
    'reports/invoice_commercial_report.xml',
    'reports/invoice_export_pro_forma_report.xml',
    'reports/invoice_local_pro_forma_report.xml',
    'reports/menu_report.xml',],
    'installable':True,
    'application':True,
    'auto_control':False,
}